In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
%pip install apyori

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5973 sha256=fd4678d8bfe927667ee6dfedfe9d192d50b89cccf44fedb12ef896bd7a381d5e
  Stored in directory: /root/.cache/pip/wheels/1b/02/6c/a45230be8603bd95c0a51cd2b289aefdd860c1a100eab73661
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [4]:
df = pd.read_csv("/content/Market_Basket_Optimisation.csv")

In [5]:
df.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   shrimp             7500 non-null   object
 1   almonds            5746 non-null   object
 2   avocado            4388 non-null   object
 3   vegetables mix     3344 non-null   object
 4   green grapes       2528 non-null   object
 5   whole weat flour   1863 non-null   object
 6   yams               1368 non-null   object
 7   cottage cheese     980 non-null    object
 8   energy drink       653 non-null    object
 9   tomato juice       394 non-null    object
 10  low fat yogurt     255 non-null    object
 11  green tea          153 non-null    object
 12  honey              86 non-null     object
 13  salad              46 non-null     object
 14  mineral water      24 non-null     object
 15  salmon             7 non-null      object
 16  antioxydant juice  3 non-null      object
 17  frozen smoothie    3 non-null      object
 18  spinach            2 non-null      object
 19  olive oil          0 non-null      float64
dtypes: float64(1), object(19)
memory usage: 1.1+ MB

In [7]:
transactions = []
for i in range(0, 5000):
  transactions.append([str(df.values[i,j]) for j in range(0, 20)])

In [8]:
from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

In [9]:
results = list(rules)
print(results)

[RelationRecord(items=frozenset({'burgers', 'almonds'}), support=0.006, ordered_statistics=[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.2912621359223301, lift=3.332518717646797)]), RelationRecord(items=frozenset({'ground beef', 'blueberries'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'blueberries'}), items_add=frozenset({'ground beef'}), confidence=0.326530612244898, lift=3.1763678233939494)]), RelationRecord(items=frozenset({'chicken', 'light cream'}), support=0.0046, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.2875, lift=4.592651757188498)]), RelationRecord(items=frozenset({'cooking oil', 'light cream'}), support=0.0036, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'cooking oil'}), confidence=0.22499999999999998, lift=3.9198606271777)]), RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.0058, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30526315789473685, lift=3.740970072239422)]), RelationRecord(items=frozenset({'escalope', 'pasta'}), support=0.0048, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.30769230769230765, lift=3.770739064856711)]), RelationRecord(items=frozenset({'extra dark chocolate', 'olive oil'}), support=0.003, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'olive oil'}), confidence=0.2459016393442623, lift=3.563791874554526)]), RelationRecord(items=frozenset({'honey', 'fresh tuna'}), support=0.0046, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fresh tuna'}), items_add=frozenset({'honey'}), confidence=0.20175438596491227, lift=4.185775642425566)]), RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.0034, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.25757575757575757, lift=5.343895385389161)]), RelationRecord(items=frozenset({'parmesan cheese', 'frozen vegetables'}), support=0.0058, ordered_statistics=[OrderedStatistic(items_base=frozenset({'parmesan cheese'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3625, lift=3.7918410041841)]), RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.0152, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.32340425531914896, lift=3.145955791042305)]), RelationRecord(items=frozenset({'herb & pepper', 'light cream'}), support=0.0032, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'herb & pepper'}), confidence=0.2, lift=4.25531914893617)]), RelationRecord(items=frozenset({'olive oil', 'light cream'}), support=0.0034, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.2125, lift=3.0797101449275357)]), RelationRecord(items=frozenset({'olive oil', 'whole wheat pasta'}), support=0.0072, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2857142857142857, lift=4.140786749482401)]), RelationRecord(items=frozenset({'shrimp', 'pasta'}), support=0.005, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.32051282051282054, lift=4.426972659016858)])]

In [10]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

In [11]:
print(resultsinDataFrame)

          Left Hand Side    Right Hand Side  Support  Confidence      Lift
0                almonds            burgers   0.0060    0.291262  3.332519
1            blueberries        ground beef   0.0032    0.326531  3.176368
2            light cream            chicken   0.0046    0.287500  4.592652
3            light cream        cooking oil   0.0036    0.225000  3.919861
4   mushroom cream sauce           escalope   0.0058    0.305263  3.740970
5                  pasta           escalope   0.0048    0.307692  3.770739
6   extra dark chocolate          olive oil   0.0030    0.245902  3.563792
7             fresh tuna              honey   0.0046    0.201754  4.185776
8          fromage blanc              honey   0.0034    0.257576  5.343895
9        parmesan cheese  frozen vegetables   0.0058    0.362500  3.791841
10         herb & pepper        ground beef   0.0152    0.323404  3.145956
11           light cream      herb & pepper   0.0032    0.200000  4.255319
12           light cream          olive oil   0.0034    0.212500  3.079710
13     whole wheat pasta          olive oil   0.0072    0.285714  4.140787
14                 pasta             shrimp   0.0050    0.320513  4.426973

In [12]:
resultsinDataFrame.nlargest(n = 10, columns = 'Lift')

          Left Hand Side    Right Hand Side  Support  Confidence      Lift
8          fromage blanc              honey   0.0034    0.257576  5.343895
2            light cream            chicken   0.0046    0.287500  4.592652
14                 pasta             shrimp   0.0050    0.320513  4.426973
11           light cream      herb & pepper   0.0032    0.200000  4.255319
7             fresh tuna              honey   0.0046    0.201754  4.185776
13     whole wheat pasta          olive oil   0.0072    0.285714  4.140787
3            light cream        cooking oil   0.0036    0.225000  3.919861
9        parmesan cheese  frozen vegetables   0.0058    0.362500  3.791841
5                  pasta           escalope   0.0048    0.307692  3.770739
4   mushroom cream sauce           escalope   0.0058    0.305263  3.740970